version: '3.9'

networks:
  default:
    name: zkevm-chain

services:
  #TODO: add additional bootnode
  leader-testnet-geth:
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/geth:latest
    restart: unless-stopped
    volumes:
      - leader-testnet-geth:/root
    ports:
      - 30303:30303
    environment:
      - MINER_PRIV_KEY
      - MINER_ADDRESS
      - GENESIS=l2-testnet
    command:
      --networkid 99
      --gcmode archive
      --unlock $MINER_ADDRESS
      --password /dev/null
      --allow-insecure-unlock
      --miner.gaslimit 4000000
      --nodiscover
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,txpool,miner,debug
      --nodekeyhex abebb96d7d9bbc99730439f230afd0008c0e0cb93eafb6874fecb256572252a4

  server-testnet-geth:
    depends_on:
      - leader-testnet-geth
    deploy:
      replicas: 2
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/geth:latest
    restart: unless-stopped
    environment:
      - MINER_ADDRESS
      - GENESIS=l2-testnet
      - BOOTNODE=enode://f28f5a7706e5aec836f3136feb7d5e7264a7f0da04ac4984f0ff2421ee1dd2b135894cf0d4f5ff8c412442b95b9bb0780a9c8a8c64de2d4a8c458586fdb20829@leader-testnet-geth:30303
    # normally those serving nodes should not serving the debug namespace + gcmode archive - only for testnet
    command:
      --networkid 99
      --gcmode archive
      --syncmode full
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,debug

  l1-testnet-geth:
    build:
      dockerfile: docker/geth/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/geth:latest
    restart: unless-stopped
    volumes:
      - l1-testnet-geth:/root
    environment:
      - MINER_PRIV_KEY
      - MINER_ADDRESS
      - GENESIS=l1-testnet
    command:
      --networkid 98
      --unlock $MINER_ADDRESS
      --password /dev/null
      --allow-insecure-unlock
      --nodiscover
      --miner.gaslimit 10000000
      --mine
      --http
      --http.addr "[::]"
      --http.port 8545
      --http.corsdomain=*
      --http.vhosts=*
      --http.api eth,net,web3,debug

  coordinator:
    init: true
    build:
      dockerfile: docker/coordinator/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/coordinator:latest
    depends_on:
      - leader-testnet-geth
      - server-testnet-geth
      - l1-testnet-geth
      - prover-rpcd
    restart: unless-stopped
    environment:
      - LISTEN=[::]:8545
      - RPC_SERVER_NODES=server-testnet-geth:8545
      - L2_RPC_URL=http://leader-testnet-geth:8545
      - L1_RPC_URL=http://l1-testnet-geth:8545
      - L1_BRIDGE=0x936a70c0b28532aa22240dce21f89a8399d6ac60
      - L1_PRIV=$MINER_PRIV_KEY
      - PROVER_RPCD_URL=http://prover-rpcd:8545
      - DUMMY_PROVER=1
      - ENABLE_FAUCET=1

  prover-rpcd:
    init: true
    build:
      dockerfile: docker/prover/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/prover:latest
    restart: unless-stopped
    environment:
      - BIND=[::]:8545
      - PARAMS_PATH=/testnet-params

  dev:
    profiles:
      - dev
    depends_on:
      - leader-testnet-geth
      - server-testnet-geth
      - l1-testnet-geth
      - prover-rpcd
    image: rust:1.61.0
    volumes:
      - .:/app
      - dev-build-cache:/app/coordinator/target:overlay
      - dev-cargo-cache:/usr/local:overlay
    environment:
      - LISTEN=[::]:8000
      - PARAMS_PATH=/app/testnet/params
      - RPC_SERVER_NODES=server-testnet-geth:8545
      - L2_RPC_URL=http://leader-testnet-geth:8545
      - L1_RPC_URL=http://l1-testnet-geth:8545
      - L1_BRIDGE=0x936a70c0b28532aa22240dce21f89a8399d6ac60
      - L1_PRIV=$MINER_PRIV_KEY
      - PROVER_RPCD_URL=http://prover-rpcd:8545
      - DUMMY_PROVER=1
      - ENABLE_FAUCET=1
    ports:
      - 8000:8000
    working_dir: /app/coordinator
    entrypoint: /bin/bash
    command: -c exit
    tty: true
    stdin_open: true

  web:
    depends_on:
      - coordinator
    restart: unless-stopped
    build:
      dockerfile: docker/web/Dockerfile
    image: ghcr.io/privacy-scaling-explorations/zkevm-chain/web:latest
    ports:
      - 8000:8000

volumes:
  dev-build-cache:
  dev-cargo-cache:
  leader-testnet-geth:
  l1-testnet-geth:
