[package]
name = "prover"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2022_08_19" }
bus-mapping = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", rev = "7d753bb6d6e01edab817a546b86c64cf60efe473" }
eth-types = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", rev = "7d753bb6d6e01edab817a546b86c64cf60efe473" }
zkevm-circuits = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", rev = "7d753bb6d6e01edab817a546b86c64cf60efe473" }
env_logger = "0.9.0"
ethers-providers = "0.6"
hyper = { version = "0.14.16", features = ["server"] }
rand_xorshift = "0.3"
log = "0.4.14"
rand = "0.8.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
strum = "0.24"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
mock = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits.git", rev = "7d753bb6d6e01edab817a546b86c64cf60efe473" }
ethers-signers = "0.6"
ethers-core = "0.6"

[features]
default = []
autogen = []
