name: Docker
on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches:
      - master

jobs:
  build:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DOCKERFILE: ['docker/coordinator/Dockerfile', 'docker/web/Dockerfile', 'docker/prover/Dockerfile', 'docker/geth/Dockerfile']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/docker-cache
          key: docker-cache-${{ runner.arch }}-${{ runner.os }}-${{ github.workflow }}-${{ matrix.DOCKERFILE }}

      - name: setup swap
        run: |
          sudo fallocate -l 8g /swapfile
          sudo chmod 0600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Login to ghcr.io
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: printf "$PAT" | docker login --username _ --password-stdin ghcr.io

      - name: Build and push Docker images
        env:
          DOCKERFILE: ${{ matrix.DOCKERFILE }}
          PLATFORM: 'linux/amd64,linux/arm64'
        run: ./.github/workflows/docker.sh

      - name: Fix docker cache
        if: success()
        run: rm -rf "$RUNNER_TEMP/docker-cache" && mv "$RUNNER_TEMP/docker-cache-new" "$RUNNER_TEMP/docker-cache"
